appd.adoc

I tried to fix all the remaining issues in Appendix D, mostly fixing formatting of variables

Fixed small issues in Appendix D

---

cf-conventions.adoc

NB. The bibliography references are dependent on #24.

Front matter fixes

---

ch02.adoc

Hi Richard and Mark,
Here are some minor format suggestions for chapter 2: spaces before commas and the like. CF-1.5 changed to CF-1.6, also.
Thanks and all the best,
David

Chapter 2 fixes

---

ch04.adoc

A rebased version of #30.
Closes #30.

Chapter 4 fixes

---

ch05.adoc

A rebased version of #31.
Closes #31.

Chapter 5 fixes

---

appa.adoc
appc.adoc
appe.adoc
appf.adoc
ch03.adoc

Manual table captions

---

appa.adoc
appc.adoc
appe.adoc
appf.adoc
ch03.adoc
ch09.adoc

Get rid of unnecessary cellbgcolor markup, and generally tidy up and simplify.
Closes #40.

Tidy table markup.

---

appa.adoc
appb.adoc
appc.adoc
appe.adoc
appf.adoc
apph.adoc
cf-conventions.adoc
ch03.adoc
ch04.adoc
ch05.adoc
ch06.adoc
ch07.adoc
ch08.adoc
toc-extra.adoc

Add lists of tables and examples.

---

appa.adoc
ch01.adoc
ch02.adoc

Slightly more controversial ... this actually updates the text of several links to reflect reality (as it currently stands).

Fix text for NUG links.

---

appa.adoc

See http://cf-trac.llnl.gov/trac/ticket/67

Apply changes from trac ticket 67.

---

appg.adoc

Revision history entry for trac ticket 67.

---

appg.adoc
cf-conventions.adoc

See http://cf-trac.llnl.gov/trac/ticket/141

Changed affiliations of Jonathan Gregory and Phil Bentley.

---

appa.adoc
appg.adoc
apph.adoc

See http://cf-trac.llnl.gov/trac/ticket/103
@rhattersley Opinion of my interpretation?

Apply changes from trac ticket 103.

---

appf.adoc
appg.adoc
cf-conventions.adoc

See http://cf-trac.llnl.gov/trac/ticket/71

Apply changes from trac ticket 71.

---

appa.adoc
appg.adoc
ch03.adoc

103 Appex a

---

appe.adoc
cf-conventions.adoc
ch07.adoc
history.adoc

This fulfills Trac ticket 102, Request for two additional cell_methods.  Other than the revision history, this branch is exactly the same as branch #102 in @reshel3 's fork.

Ticket 102, Request for two additional cell_methods.

---

ch01.adoc
ch05.adoc
ch06.adoc
ch09.adoc
history.adoc

This has all the changes of ticket 104, as described in comments 64 and 66.  Most of the changes had been in @reshel3 's branch #104 in her fork, but this branch has a couple very minor revisions, and comment 66 is newly implemented in this branch.

Ticket 104, Clarify the interpretation of scalar coordinate variables

---

ch05.adoc

I restored a missing sentence which had been deleted by mistake.  Thank you for catching this, @davidhassell !  While I was at it I inserted a couple of cross-references.

correction Ticket 104, Clarify the interpretation of scalar coordinate variables

---

ch05.adoc
history.adoc

Chapter 5 is revised as specified in Ticket 70.
However, the consequent new Example 5.10 is no longer consistent with Example 5.12.  So I also merged the old Example 5.10 into Example 5.12, and made the necessary small changes in the associated text.

Ticket 70, Connecting coordinates to Grid Mapping variables

---

ch03.adoc

See http://cf-trac.llnl.gov/trac/ticket/66, comment 1 (by Jonathan Gregory).
This is a defect ticket, and this clarification requires only a slight change.

Implement clarification stated in comment 1 of ticket 66.

---

apph.adoc

c.f. Charlie Zender's email to the cf-metadata list of 2017-April-25.

Fix typos found by Charlie Zender

---

ch07.adoc
history.adoc

Ticket #140, Added 3 paragraphs and an example to Chapter 7, Section
7.1.

Ticket #140

---

appd.adoc
toc-extra.adoc

I replaced Table D.1 with one formatted as requested by Karl Taylor.

New Table D.1 format

---

appf.adoc
bibliography.adoc
ch05.adoc

See http://cf-trac.llnl.gov/trac/ticket/162
I'm aware this is late to the party.  I have raised a Trac ticket regarding this, I wanted to capture the details inside github as well
@painter1 where are we in the time line for adopting CF1.7 please?
I can see from
https://github.com/cf-convention/cf-conventions/pull/119
that 'master' is the 'Final draft'
is master still accepting editorial/defect changes?
is master accepting material changes?
clearly we'll want a view from the community on whether this is material or editorial
many thanks
mark

use up to date OGC reference to WKT-CRS

---

ch05.adoc

See http://cf-trac.llnl.gov/trac/ticket/162

use up to date WKT-CRS syntax

---

.travis.yml
CONTRIBUTING.md
appf.adoc
bibliography.adoc

See issue #170 for discussion.

update contributing fixes #170 and fix travis build for #175

---

ch07.adoc
history.adoc

Alternate grid mappings for geometry containers
https://github.com/cf-convention/cf-conventions/issues/156
Specify Geometry Dimension on Geometry Container
https://github.com/cf-convention/cf-conventions/issues/155

geometry updates

---

cf-conventions.adoc

See issue #144 for discussion of these changes. This PR is intended to work on top of #145 - it is a simple clerical update. @dblodgett-usgs as discussed.

Add authors of Groups proposal

---

appf.adoc
bibliography.adoc
cf-conventions.adoc

Some minor improvements, fixing a bibliography issue and improving the pdf version of the document.

Formal improvements

---

.travis.yml

See issue #177 or discussion of these changes.

update bot token

---

appf.adoc
ch05.adoc
ch09.adoc

See issue #186 for discussion of these changes.

Correction of some inconsistencies

---

.github/ISSUE_TEMPLATE/enhancement-issue.md

Updates to enhancement issue template in line with modified rules on moderation as discussed in cf-convention/cf-conventions#151

Updates to enhancement issue template

---

appf.adoc

See issue #213 for discussion of these changes.

added plural-s to some values; fixed #213

---

.github/ISSUE_TEMPLATE/defect-issue.md
.github/ISSUE_TEMPLATE/enhancement-issue.md

See issue #228 for discussion of these changes.

Use sections not formatting to allow paragraphs

---

history.adoc

See issue #233 for discussion of these changes.

Revision history 1.8

---

conformance.adoc

See issue #226 for discussion of these changes.

2.3 must -> should

---

ch03.adoc
toc-extra.adoc

Also, fix broken link in List of Examples
See issue #238 for discussion of these changes.
Fixes #238.
For consideration either before 1.8 docs are released or hopefully in a patch release subsequently if these have missed deadlines for inclusion in 1.8.

Resolve Example 3.4 and 3.5 mis-ordering issue

---

README.md

add latest spec build info to READEME

---

appf.adoc

See issue #241 for discussion of these changes.

Explicitly specify earth shape parameters

---

.github/ISSUE_TEMPLATE/defect-issue.md
.github/ISSUE_TEMPLATE/enhancement-issue.md
.github/ISSUE_TEMPLATE/github-usage-issue.md
.github/ISSUE_TEMPLATE/style-issue.md
.github/ISSUE_TEMPLATE/typo-issue.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

See issue #172 for discussion of these changes.
This PR attempts to find procedural changes that don't touch the constitution and have been discussed in the referenced issue extensively. I will open a separate issue in order to recommence discussion on these items.

Procedural items

---

ch02.adoc

This PR contains some rewording agreed towards the end of issue #243 discussion that I evidently never pushed to PR #244 . 
@erget - You were the moderator on #243. Sorry for the confusion. I will reopen #243 and link to this PR. Maybe we restart the 3-week count down?

Minor changes from Issue 243 (adding integer types) that didn't make it into PR 244

---

cf-conventions.adoc
ch04.adoc
conformance.adoc
history.adoc

See issue #313 for discussion of these changes.

Leap seconds clarification

---

appd.adoc
conformance.adoc
history.adoc

Fixes: #314
See issue https://github.com/cf-convention/cf-conventions/issues/314 for discussion of these changes.

Sigma pr317

---

conformance.adoc

See issue #336 for discussion of these changes.

Fix syntax error

---

cf-conventions.adoc

No associated issue - editorial fix.

Include new authors in top-level author list

---

history.adoc

Update history ready for CF-1.9

---

.github/workflows/adoc_build.yml
cf-conventions.adoc
ch01.adoc
ch02.adoc
conformance.adoc
version.adoc

See issue #343 for discussion of these changes.

Single source version

---

.github/ISSUE_TEMPLATE/github-usage-issue.md

Self-referential, might make GitHub blow up!

Fixes #363

---

CONTRIBUTING.md

Fixes #362

---

history.adoc

See issue #345 for discussion of these changes.
- [NA ] Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).

Reformat history

---

ch07.adoc

missing ; (typo)

---

appi.adoc
appj.adoc
ch07.adoc
ch08.adoc

Fix the broken images

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

@sadielbartholomew happy with these?

Apply line break policy

---

ch01.adoc
ch03.adoc
ch04.adoc
ch07.adoc
conformance.adoc
history.adoc

Reverts cf-convention/cf-conventions#390

Revert "UDUNITS clarifications from workshop housekeeping 2022"

---

history.adoc

update history for issue 410

---

ch03.adoc
conformance.adoc
history.adoc

See https://github.com/cf-convention/cf-conventions/issues/260 for discussion of these changes.
- [Y] Conformance document up-to-date?

Clarify dimensionless units

---

appf.adoc
history.adoc

See issue [discuss/#189](https://github.com/cf-convention/discuss/issues/189) for discussion of these changes.

Fixes discuss/#189

---

ch09.adoc
history.adoc

See [issue 430](https://github.com/cf-convention/cf-conventions/issues/430) for discussion of these changes.
- [NA ] Authors updated in `cf-conventions.adoc`?

clarify the function of the `cf_role` attribute

---

conformance.adoc

See issue #406 for discussion of these changes.
- [n/a ] Authors updated in `cf-conventions.adoc`?
- [n/a ] Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).
- [n/a ] `history.adoc` up to date?
- [Y] Conformance document up-to-date?

Remove duplicate section 8.2 

---

cf-conventions.adoc
ch04.adoc
conformance.adoc
history.adoc

See issue #405 for discussion of these changes.

Fix issue #405 (draft)

---

appd.adoc
apph.adoc
appi.adoc
ch05.adoc
ch08.adoc
history.adoc
toc-extra.adoc

See issue #286 for discussion of these changes.

Rename some examples for consistency

---

ch03.adoc
history.adoc

See issue #367 for discussion of these changes.

delete obsolete references in sect 3.3

---

bibliography.adoc

See issue #391, in particular this [comment](https://github.com/cf-convention/cf-conventions/issues/391#issuecomment-1715576325), for discussion of these changes.
- _N/A_ Authors updated in `cf-conventions.adoc`?
- _N/A_ Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).
- _N/A_ `history.adoc` up to date?  --- _reusing previous issue_
- _N/A_ Conformance document up-to-date?

Replace the USGS link to Snyder with the DOI

---

bibliography.adoc
history.adoc

See issue #266 for discussion of these changes.

updates to some links in the bibliography

---

apph.adoc
history.adoc

See issue #210 for discussion of these changes.

correct errors in examples H9-H11

---

history.adoc
toc-extra.adoc

See issue #420 for discussion of these changes.
Tags are set at the conclusion of the annual meeting; until then `main` always is a draft for the next version.

List of figures

---

ch02.adoc
history.adoc

I just saw a broken link and found a valid replacement.
See https://github.com/cf-convention/cf-conventions/issues/458.

Fix broken link

---

.github/PULL_REQUEST_TEMPLATE.md

Minor change
NO issue for discussion of these changes.

master -> main

---

appd.adoc
history.adoc

See issue #472 for discussion of these changes.

Fix incorrect formating for some `<=` in Appendix D

---

history.adoc

Just completing PR#464 related to issue #383. Sorry for the confusion.

Add forgotten update to the history in PR#464

---

cf-conventions.adoc

See issue #484 for discussion of these changes.

Fix affiliation for Dave Allured

---

ch02.adoc
conformance.adoc
history.adoc

See issue #468 for discussion of these changes.

Update section 2.3  to clarify allowed character set

---

ch06.adoc
history.adoc

See issue #490 for discussion of these changes.

Updated the standard name in Example 6.1.2

---

appj.adoc
ch08.adoc
conformance.adoc
history.adoc

See issue #486 for discussion of these changes.

Asciidoc fixes

---

LICENSE.md

See issue cf-convention/cf-convention.github.io#182 for discussion of these changes.
- [N/A] Authors updated in `cf-conventions.adoc`? Add in two places: on line 3 and under `.Additional Authors` in `About the authors`.
- [N/A] Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).
- [N/A] `history.adoc` up to date?
- [N/A] Conformance document up to date?

Add LICENSE.md file to specify CC0 license.

---

appa.adoc
ch03.adoc
ch09.adoc
conformance.adoc
history.adoc

See issue #501 for discussion of these changes.
- [Y] Conformance document up to date?

clarify various issues relating to attributes

---

ch08.adoc

- [] `history.adoc` up to date?

Fixing anchor to Figure 8.7

---

ch01.adoc
ch02.adoc
ch07.adoc
history.adoc

See issue #530 for discussion of these changes.

Define "the most rapidly varying dimension"

---

appa.adoc
ch01.adoc
ch02.adoc
ch03.adoc
ch04.adoc
conformance.adoc
history.adoc
toc-extra.adoc

merge from leap-seconds branch

Leap seconds

---

appa.adoc
ch01.adoc
ch02.adoc
ch03.adoc
ch04.adoc
conformance.adoc
history.adoc
toc-extra.adoc

I am recommitting the versions of the files I modified by accident. I obtained these versions from the repository as it was after #519 was merged.

reverse b5f0e91 at 1134 UTC today, done by accident

---

.github/gh-pages/index.html
.github/workflows/adoc_build.yml
Makefile
README.md
images/order_horizontal_bounds__1D_coord_variables.R
images/order_horizontal_bounds__2D_coord_variables.R

See NO-issue for discussion of these changes.
- [NA] `history.adoc` up to date?

Updating build and publish

---

ch07.adoc

See issue #587 for discussion of these changes.

Fix :cell_methods to be a single string.

---

ch01.adoc
history.adoc

See issue #583 for discussion of these changes.

Correct "most rapidly varying dimension"

---

appa.adoc
ch03.adoc
ch07.adoc
conformance.adoc
history.adoc

See issue #593 for discussion of these changes.

Bi attributes for climatology bounds

---

README.md

See issue #602 for discussion of these changes.

Adding DOI badge to the repository landing page
