cf-convention/cf-conventions

- pr01.adoc
Tidy-up syntax and clarify revision history status.
Closes #14.
> Preface fixes

- pr01.adoc
Dear Richard
I respect your respecting the existing text! I think that's the right thing to do regarding the conventions, but since this new version may well supersede the existing 1.6 document, or be maintained together with it, I think it makes sense to correct the link.
Best wishes
Jonathan
> correct the CF link

- appa.adoc
As can be seen with all the other bibliography references, the square brackets come for free now.
> Fix reference to COARDS.

- cf-conventions.adoc
Unlike the other appendices, appendix H does use numbers for the section & sub-sections.
> Turn on numbering for Appendix H.

- cf-conventions.adoc
- no-lead-theme.yml
It's not yet possible to specify the position of the table of contents when producing the PDF document. So instead, this PR modifies the structure of the document to fit the fixed location of the table of contents.
1. Allows the HTML & PDF versions to have the same structure.
2. Allows the lists of tables & examples to follow the table of contents in the PDF document.
Previews of the new structure are available at:
- http://cf-metadata.github.io/moved-toc.html
- http://cf-metadata.github.io/moved-toc.pdf
It's not clear whether this new structure is an improvement. Feedback welcome!
> Move table of contents to start of document.

- .travis.yml
A change to the master branch will be reflected at http://cf-metadata.github.io/cf-conventions/, a tag will be in a sub-directory named after the tag, e.g. http://cf-metadata.github.io/cf-conventions/v1.6/.
> Target builds at gh-pages branch.

- apph.adoc
A follow-up to #72, which fixes the link title shown for cross-references to Appendix H.
Currently a cross-reference to appendix H shows as:
> "In _Annotated Examples of Discrete Geometries_, updated ... "
but this PR changes it to bring it in line with all the other appendices:
> "In _Appendix H, Annotated Examples of Discrete Geometries_, updated ... "
> Fix link title for appendix H

- appf.adoc
- history.adoc
This has the changes specified in ticket 75, except for the urls and related text.
Please do not merge this pull request until we have correct urls, and surrounding text.
The ticket's urls are now invalid.  For lambert_conformal_conic, I replaced the two urls with a more generic reference to http://proj4.org/projections.  For polar_stereographic, I have made no replacement.  Proj4.org lists "universal polar stereographic" which I think might be slightly different from "polar stereographic"; I need more advice here.
For all grid mappings, the grid-mapping-specific text at proj4.org is extremely terse, briefer than the references to it in Appendix F!
> Changes required by ticket #75

- appa.adoc
- ch02.adoc
These changes are small, and clarify some statements about external variables.  They were added to Ticket 145 after it had been officially approved, but the changes have enough support so that they are part of the final version of Ticket 145.
> Last comments of Ticket 145.

- appa.adoc
- bibliography.adoc
- ch01.adoc
- ch02.adoc
- history.adoc
. Updated the links and references to NUG (The NetCDF User Guide), to refer to the current version.
. Trivial updates to links for COARDS and UDUNITS in the bibliography.
I didn't create a Trac ticket for this because it is highly non-controversial.
> Updated links and references to NUG

- ch06.adoc
- toc-extra.adoc
Fix for bad reference to an example in section 6.1 "Labels". Also update numbering of examples in chapter 6.
See http://cf-trac.llnl.gov/trac/ticket/XXX
> Fix bad reference to an example in section 6.1 "Labels"

- apph.adoc
coordinates attribute refers to an undefined variable altz, which doesn't exist as a variable or anything else, afaict, but z does.
> change altz to z in :coordinates attribute

- apph.adoc
This addresses CF Trac ticket #[161](http://cf-trac.llnl.gov/trac/ticket/161), "h.2 name_strlen". That ticket points out one example of a missing `name_strlen` dimension definition. This PR fixes that instance and several others.
> Add definition of 'name_strlen' dimension where missing in Appendix H CDL examples

- README.md
- cf-conventions.adoc
Just a little housekeeping. Clarifying how the automated build works in the readme and updating the version of the spec to 1.8 (draft) in the title.
> update readme and add 1.8 (draft) to title

- apph.adoc
Variable trajectory uses dimension trajectory, which was missing.
See issue #136 for discussion of these changes.
> Missing dimension trajectory in H.22

- ch01.adoc
- ch02.adoc
Variable and dimension names can be either a single variable name or a path to a variable
Add definition of path
Recommend that group names follow the same convention as variable and dimension names (ie. that they are composed of letters, digits and underscores)
See issue #203 for discussion of these changes.
> Clarification to use of groups

- appf.adoc
The projection parameters `false_easting` and `false_northing` should be considered as optional for all projections. If they do not exist, they should be assumed to be `0`. This was added to the definitions of these parameters.
See issue #212 for discussion of these changes.
> Update usage of false_easting and false_northing in projections

- ch05.adoc
See issue #223  for discussion of these changes.
Fixes #223 
Provides a mechanism to specify explicit 'Axis Order' for use with CRS WKT using enhanced interpretation of existing syntax
> coord value order for CRS WKT

- cf-conventions.adoc
Hello @painter1 @davidhassell 
I think that this PR is editorial only. It simply updates the version string to 1.9 (draft), to ensure that the nightly build of latest is not version stamped as 1.8, now that the 1.8 tag is minted and published.
I hope this is a useful and timely step
thank you
mark
> set version string to 1.9 (draft)

- appf.adoc
- history.adoc
See issue #230 for discussion of these changes.
> Fix geostationary projection

- .github/workflows/check_adoc_build.yml
This PR enables a github action to check that PRs do not break the asciidoc build. If the build is successful, the pdf and html files are uploaded as artifacts to the action, which allow for easier previews of the generated files.
> Check that PRs do not break Asciidoctor build

- apph.adoc
- ch02.adoc
- ch09.adoc
See issue #243 for discussion of these changes.
> Add new integer types in CF 2.2 Data Types (#243)

- bibliography.adoc
No corresponding issue, as this is a uncontroversial one-line change to fix a broken link.
See also Issue cf-convention/cf-convention.github.io#74 which registers an equivalent reference to the obsolete URL on the website, & where I have commented regarding the choice of replacement link (in short, with a change of the path as well as for the new NOAA Ferret host, the same content is kept included but high-up on the core sitemap).
> Amend broken link (RE COARDS Conventions) in bibliography

- appf.adoc
See issue #253 for discussion of these changes in [Appendix F: Grid Mappings](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#appendix-grid-mappings) of the CF Conventions:
* Replace `PROJ.4` by `PROJ`.
* Replace `http://proj4.org/projections/` by `https://proj.org/operations/projections/`.
* Some projections are missing a link to the corresponding description in the PROJ-manual. Add these links.
> replaced PROJ.4 by PROJ; updated URLs; fixed #253

- ch03.adoc
- toc-extra.adoc
Replaces: #235
See issue #216 for discussion of these changes, specifically in [this comment](https://github.com/cf-convention/cf-conventions/issues/216#issuecomment-564107540) suggesting adding to the CF documentation usage examples for status_flag, quality_flag, and related QC flag standard names proposed in #216.
This PR includes the following:
- adds to Chapter 3.4 new text describing usage of ancillary variables as status/quality flags, and a new Example 3.3 illustrating their use
- adds `status_flag` attributes to Example 3.5 as suggested in #216 and earlier discussions in the CF mailing list surrounding the addition of `quality_flag`.  See [this thread](http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2019/020995.html) in the CF list archives for related discussion.
> Chap 34 ancillary quality flags

- apph.adoc
In some examples where only `string` type is been used, there is a dimension `name_strlen` which it's unnecesary.
> Removing unnecessary dimensions

- cf-conventions.adoc
- ch05.adoc
- history.adoc
The three weeks have gone by without complaint, so I am moving forward with this change.
> Allow CRS WKT to represent the CRS without requiring reader to compare with grid mapping parameters

- conformance.adoc
Clarification to conformance document for region names/area_types to allow use of flag_values and flag_meanings as per discussion in #198.  This was a PR that got missed before the conformance document was moved into the cf-conventions repository.
See issue #198 for discussion of these changes.
> Conformance clarification for  region name/area types

- conformance.adoc
See issue #139 for discussion of these changes.
This was a missed PR in the conformance repo before it was moved into the cf-conventions repo  (cf-convention/Conformance#7)
> Add support for variables of type string to conformance doc

- cf-conventions.adoc
- conformance.adoc
I think we missed this in the release process. Or maybe we haven't done this in the past.
I didn't change the date next to the version number at the top of the conventions document.
> Post-release update of version number in draft documents to "1.10 draft"

- apph.adoc
- history.adoc
See issue #162 for discussion of these changes.
> delete incorrect missing_data attributes of time coordinate variables in two examples

- history.adoc
No associated issue - just adding to the history changes that had not been recorded before.
- NA Authors updated in `cf-conventions.adoc`?
- NA Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).
- NA Conformance document up-to-date?
> Add missing history items for CF-1.10

- .github/workflows/adoc_build.yml
See issue #388 for discussion of these changes.
> Fix escaping in single sourcing of version

- ch01.adoc
- ch03.adoc
- ch04.adoc
- ch07.adoc
- conformance.adoc
- history.adoc
See issue #385  for discussion of these changes.
> UDUNITS clarifications from workshop housekeeping 2022

- appf.adoc
See issues https://github.com/cf-convention/cf-conventions/issues/410 and https://github.com/cf-convention/discuss/issues/188 for discussion of these changes
> Delete "on a spherical Earth" from the definition of the `latitude_longitude` grid mapping in Appendix F

- apph.adoc
- cf-conventions.adoc
- ch05.adoc
- ch08.adoc
- ch09.adoc
- conformance.adoc
- history.adoc
See issue #428 for discussion of these changes.
It is quite common that the deployment position of a station changes after maintenance or repositioning after it drifts. Example H.5. "A single timeseries with time-varying deviations from a nominal point spatial location" has been extended to show how these deployments can be encoded in CF. Lossless compression by gathering is applied to the deployment coordinate variables, which otherwise would contain a lot of missing or repetitive data. 
- Appendix H has been modified to extend Example H.5
- Section 5 and conformance modified to add a new exception to consider also dimensions in the compress attribute of the auxiliary coordinate.
- Section 8.2 modified to add more information and reference Example H.5
- Section 9 updated to correct a …
> Cf conventions deployment position

- cf-conventions.adoc
I added a new author to the list but I forgot to add it to the header. This pull request complements <Recording deployment positions #428>
For more information: 
https://github.com/cf-convention/cf-conventions/issues/428
- [ X] Authors updated in `cf-conventions.adoc`?
> Added author to the header

- appd.adoc
- appi.adoc
- ch02.adoc
- ch03.adoc
- history.adoc
- toc-extra.adoc
* added several examples to the list of examples
* Example I.1 now has the caption "Example I.1"
* caption "Examples 1.1. " was changes to "Example 2.1. " (because it is in chapter/section 2 and not in chapter/section 1)
* changed "5.13." to "5.14." because a new examples 5.13 was inserted
* appended a space to caption `"Table D.1."` => `"Table D.1. "`
* added captions `Table I.1. ` and `Table I.1. `
* added a `.` to a caption in chapter 3
* updated history
See issue #418 for discussion of these changes. Replaces #419 .
Tags are set at the conclusion of the annual meeting; until then `main` always is a draft for the next version.
> added examples to TOE; updated captions

- ch07.adoc
- history.adoc
Fix end-date of 2007-2008 Winter to be in 2008 in Example 7.12.
> Update ch07.adoc, fix typo in example 7.12

- ch08.adoc
- conformance.adoc
- history.adoc
See issue #374 for discussion of these changes.
- [Y] Conformance document up-to-date?
> Clarify rules for packing and unpacking in Section 8.1

- CONTRIBUTING.md
> Insert missing 'and' in CONTRIBUTING.md

- appd.adoc
- apph.adoc
- ch01.adoc
- ch09.adoc
- history.adoc
Update text in convention document to consistently use "strictly monotonic" instead of "monotonic" when describing coordinate variables.
See issue #423 for discussion of these changes.
Tags are set at the conclusion of the annual meeting; until then `main` always is a draft for the next version.
> Always use "strictly monotonic" when describing coordinate variables

- apph.adoc
Minor fix on text alignment. Doesn't change the meaning of the content. No associated issue for such a minor change.
> Minor fix on  text alignment

- appf.adoc
In Table F.1, left column, rogue spaces made the backticks not work properly for attributes `fixed_angle_axis` and `sweep_angel_axis`.
> deleted rogue spaces in table F.1 (left column)

- .github/ISSUE_TEMPLATE/defect-issue.md
- .github/ISSUE_TEMPLATE/enhancement-issue.md
- .github/ISSUE_TEMPLATE/github-usage-issue.md
- .github/ISSUE_TEMPLATE/question-issue.md
- .github/ISSUE_TEMPLATE/style-issue.md
- .github/ISSUE_TEMPLATE/typo-issue.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- appa.adoc
- appb.adoc
- appf.adoc
- bibliography.adoc
- ch01.adoc
- ch02.adoc
- ch03.adoc
- ch06.adoc
- conformance.adoc
- history.adoc
See issue #463 for discussion of these changes.
> Convert all referenced URLs with HTTP protocol to HTTPS

- cf-conventions.adoc
- history.adoc
See issue #483 for discussion of these changes.
> Add a missing author to the list

- .github/workflows/adoc_build.yml
- cf-conventions.adoc
- history.adoc
See issue #457 for discussion of these changes.
***Please note that this PR includes changes to the github workflow made by a non-expert*** 
> Automate document production date

- .github/PULL_REQUEST_TEMPLATE.md
~~See issue #XXX for discussion of these changes.~~
See https://github.com/cf-convention/cf-conventions/pull/489#issuecomment-1827828116 for the context behind the core update, which is to state to be explicit that there are two places where names should be updated in the `cf-conventions.adoc` document, preventing confusion in future that led to separate PRs being required to add names again.
Since this is an infrastructure tweak, the release checklist is not applicable so I have quoted it to effectively comment it out.
@larsbarring I have assigned you as reviewer since you are quite active on this repo of late, but feel free to re-assign should you wish. I don't think the change is controversial but will need someone to approve it regardless to confirm it's OK. Thanks.
> # Release …
> Minor update to PR template community file

- .github/workflows/adoc_build.yml
- cf-conventions.adoc
~~See issue #XXX for discussion of these changes.~~
This PR, which has no associated issue,  is intended to do two things: 
* Activate the html link to https://cfconventions.org in the "version line" (below author list) of the html document. 
* Change the spaces in the text related to the same html link to non-breaking spaces so that a possible line break in the pdf version does not chop up the text (this should have been done already in PR#464.  
> Technical updates to front page "version line"

- .github/workflows/adoc_build.yml
- ch02.adoc
- ch03.adoc
~~See issue #XXX for discussion of these changes.~~
Formatting improvement: a few malformed external links have been updated to render correctly. Suggest no history entry is needed.
> Fix malformed external links

- .github/workflows/adoc_build.yml
~See issue #XXX for discussion of these changes.~
Update GitHub actions to use  `actions/checkout@v3`, `actions/upload-artifact@v3`, and `actions/download-artifact@v3 (from `v2`) to remove the following type of report from the actions:
```
The following actions uses node12 which is deprecated and will be forced to
run on node16: actions/checkout@v2, actions/upload-artifact@v2.
For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
> Update to `actions/...@v3`

- appa.adoc
- ch03.adoc
See issue #496 for discussion of these changes.
> corrections to units_metadata text

- history.adoc
~See issue #XXX for discussion of these changes.~
> Update revision history headings for CF-1.11

- ch02.adoc
- conformance.adoc
- history.adoc
See issue #477 for discussion of these changes.
> Allow period and hyphen in attribute names

- appb.adoc
- history.adoc
See issue #509 for discussion of these changes.
- `N/A` Authors updated in `cf-conventions.adoc`? Add in two places: on line 3 and under `.Additional Authors` in `About the authors`.
- `N/A` Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).
- `N/A` Conformance document up to date?
> Appendix B: In exceptional cases allow a standard name to be aliased into two alternatives

- appb.adoc
- history.adoc
See issue #511 for discussion of these changes.
[N/A]  Authors updated in `cf-conventions.adoc`? Add in two places: on line 3 and under `.Additional Authors` in `About the authors`.
[N/A] Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).
[N/A] Conformance document up to date?
> Appendix B: New element in XML file header to record the "first published date"

- appf.adoc
- history.adoc
This is a link fixing 
- [] `history.adoc` up to date?
> Fix trac links

- ch02.adoc
- history.adoc
See issue #237 for discussion of these changes.
> Clarify that the character set given in section 2.3 for variable, dimension, attribute and group names is a recommendation, not a requirement

- ch02.adoc
(I haven't opened an issue for discussion of these changes because it is a small typo)
Not sure what needs doing with the checklist below as this is a very minor typo!
> Fix typo 'principal' -> 'principle' in ch02

- ch01.adoc
- conformance.adoc
- history.adoc
See issue #174 for discussion of these changes.
- [Y] Conformance document up to date?
>  A one-dimensional string-valued variable must not have the same name as its dimension

- ch03.adoc
- ch04.adoc
- history.adoc
See issue #166 for discussion of these changes.
> clarification of time coordinate requirements

- ch07.adoc
See issue #274 for discussion of these changes.
- [NA] `history.adoc` up to date? - No need to update, because this simply corrects a defect.
> Clarification of position of comment in `cell_methods`

- history.adoc
See issue #545 for discussion of these changes.
> correct mistakes in history

- README.md
See issue [NA] for discussion of these changes.
- [ NA] Authors updated in `cf-conventions.adoc`? Add in two places: on line 3 and under `.Additional Authors` in `About the authors`.
- [NA] `history.adoc` up to date?
> Fix and remove READM.md

- appb.adoc
- history.adoc
See issue #367 for discussion of these changes.
> Remove GRIB and AMIP information from the format of the standard name table

- ch02.adoc
- conformance.adoc
- history.adoc
See issue #141 for discussion of these changes.
- [Y] Conformance document up to date?
> Clarification that text-valued variables and attributes can be Unicode strings or UTF-8 `char` arrays

- appf.adoc
- bibliography.adoc
See issue #537 for discussion of these changes.
- [NA] `history.adoc` up to date?
> Update link to CR-WKT mapping

- ch02.adoc
- conformance.adoc
- history.adoc
* Revert PR #478.
* Remove this single line from [section 2.3, Naming Conventions](http://cfconventions.org/cf-conventions/cf-conventions.html#_naming_conventions):
"ASCII period (.) and ASCII hyphen (-) are also allowed in attribute names only."
* See issue #548 for discussion of these changes.
> ch02: Revert PR 478, period and hyphen in names

- cf-conventions.adoc
See issue #573 for discussion of these changes.
- [Y] Authors updated in `cf-conventions.adoc`? Add in two places: on line 3 and under `.Additional Authors` in `About the authors`.
- [NA] `history.adoc` up to date?
> change order of additional authors

- .zenodo.json
- CITATION.cff
- appi.adoc
- appj.adoc
- cf-conventions.adoc
- ch03.adoc
- ch07.adoc
- history.adoc
- toc-extra.adoc
- version.adoc
> Editorial changes for the CF-1.12 release documents

- ch04.adoc
- ch07.adoc
See issue #584 for discussion of these changes.
NOTE: I *think* there's consensus about allowing "Z" as a timezone offset (already allowed by udunits)
It was decided to include a "proper" recommendation that a zero or Z be included for UTC times -- but some text was added saying it is a good idea in some cases.
** Will do this once we've all agreed **
> WIP: added text allowing "Z" for timezone offset.

- cf-conventions.adoc
- ch05.adoc
- history.adoc
Discussion item [380](https://github.com/orgs/cf-convention/discussions/380) was concerned several topics related to bound variables. Some of the decisions from that discussion were already brought to the CF-1.12. This PR introduces one of the last agreed edits (https://github.com/orgs/cf-convention/discussions/380#discussioncomment-11591324).
Note that this is my first PR to the CF repo, so please bare with me :-) I am for example aware that I am creating a PR out of a Discussion item, while the contributing guidelines state there should be an Issue in between. Let me know if I must create the Issue.
> In Chapter 5.6, grid_mapping can also be used for converting spatial bounds
